class RandomBible{
  static const List<String> verseList = [
    'But now, this is what the Lord says— he who created you, Jacob, he who formed you, Israel: “Do not fear, for I have redeemed you; I have summoned you by name; you are mine. When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you When you walk through the fire, you will not be burned; the flames will not set you ablaze.',
    'Since you are precious and honored in my sight, and because I love you, I will give people in exchange for you, nations in exchange for your life. 5 Do not be afraid, for I am with you; I will bring your children from the east and gather you from the west.',
    'Do not tremble, do not be afraid. Did I not proclaim this and foretell it long ago? You are my witnesses. Is there any God besides me? No, there is no other Rock; I know not one.',
    'This is what the Lord says— he who made you, who formed you in the womb, and who will help you: Do not be afraid, Jacob, my servant, Jeshurun,[a] whom I have chosen.',
    'But Israel will be saved by the Lord with an everlasting salvation; you will never be put to shame or disgraced, to ages everlasting.',
    '10 So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand. 11 “All who rage against you will surely be ashamed and disgraced; those who oppose you will be as nothing and perish. 12 Though you search for your enemies, you will not find them. Those who wage war against you will be as nothing at all. 13 For I am the Lord your God who takes hold of your right hand and says to you, Do not fear; I will help you. 14 Do not be afraid, you worm Jacob, little Israel, do not fear, for I myself will help you,” declares the Lord, your Redeemer, the Holy One of Israel.',
    '8 “Assyria will fall by no human sword; a sword, not of mortals, will devour them. They will flee before the sword and their young men will be put to forced labor. 9 Their stronghold will fall because of terror; at the sight of the battle standard their commanders will panic,” declares the Lord, whose fire is in Zion, whose furnace is in Jerusalem.',
    '20 It will be a sign and witness to the Lord Almighty in the land of Egypt. When they cry out to the Lord because of their oppressors, he will send them a savior and defender, and he will rescue them.',
    '24 The Lord Almighty has sworn, “Surely, as I have planned, so it will be, and as I have purposed, so it will happen.',
    '19 They will fight against you but will not overcome you, for I am with you and will rescue you,” declares the Lord.',
    '7 But the Lord said to me, “Do not say, ‘I am too young.’ You must go to everyone I send you to and say whatever I command you. 8 Do not be afraid of them, for I am with you and will rescue you,” declares the Lord. 9 Then the Lord reached out his hand and touched my mouth and said to me, “I have put my words in your mouth.',
    '5 Then will the eyes of the blind be opened and the ears of the deaf unstopped.',
    '16 Look in the scroll of the Lord and read: None of these will be missing, not one will lack her mate. For it is his mouth that has given the order, and his Spirit will gather them together.',
    '37 For no word from God will ever fail.',
    '27 Jesus looked at them and said, “With man this is impossible, but not with God; all things are possible with God.',
    '37 People were overwhelmed with amazement. “He has done everything well,” they said. “He even makes the deaf hear and the mute speak.',
    '40 A man with leprosy[a] came to him and begged him on his knees, “If you are willing, you can make me clean.” 41 Jesus was indignant.[b] He reached out his hand and touched the man. “I am willing,” he said. “Be clean!” 42 Immediately the leprosy left him and he was cleansed.',
    '32 That evening after sunset the people brought to Jesus all the sick and demon-possessed. 33 The whole town gathered at the door, 34 and Jesus healed many who had various diseases. He also drove out many demons, but he would not let the demons speak because they knew who he was.',
    '35 That day when evening came, he said to his disciples, “Let us go over to the other side.” 36 Leaving the crowd behind, they took him along, just as he was, in the boat. There were also other boats with him. 37 A furious squall came up, and the waves broke over the boat, so that it was nearly swamped. 38 Jesus was in the stern, sleeping on a cushion. The disciples woke him and said to him, “Teacher, don’t you care if we drown?” 39 He got up, rebuked the wind and said to the waves, “Quiet! Be still!” Then the wind died down and it was completely calm. 40 He said to his disciples, “Why are you so afraid? Do you still have no faith?” 41 They were terrified and asked each other, “Who is this? Even the wind and the waves obey him!',
    '27 When she heard about Jesus, she came up behind him in the crowd and touched his cloak, 28 because she thought, “If I just touch his clothes, I will be healed.” 29 Immediately her bleeding stopped and she felt in her body that she was freed from her suffering.',
    '36 Overhearing[a] what they said, Jesus told him, “Don’t be afraid; just believe.',
    '40 Then Jesus said, “Did I not tell you that if you believe, you will see the glory of God?',
    '24 I told you that you would die in your sins; if you do not believe that I am he, you will indeed die in your sins.',
    '12 When Jesus spoke again to the people, he said, “I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.',
    '35 Now a slave has no permanent place in the family, but a son belongs to it forever. 36 So if the Son sets you free, you will be free indeed.',
    '10 Jesus straightened up and asked her, “Woman, where are they? Has no one condemned you?',
    '8 But as for me, I am filled with power, with the Spirit of the Lord, and with justice and might, to declare to Jacob his transgression, to Israel his sin.',
    '10 Bring the whole tithe into the storehouse, that there may be food in my house. Test me in this,” says the Lord Almighty, “and see if I will not throw open the floodgates of heaven and pour out so much blessing that there will not be room enough to store it.',
    '14 You ask, “Why?” It is because the Lord is the witness between you and the wife of your youth. You have been unfaithful to her, though she is your partner, the wife of your marriage covenant.',
    '6 “I the Lord do not change. So you, the descendants of Jacob, are not destroyed.',
    '21 I will tear off your veils and save my people from your hands, and they will no longer fall prey to your power. Then you will know that I am the Lord.',
    '23 Yet a time is coming and has now come when the true worshipers will worship the Father in the Spirit and in truth, for they are the kind of worshipers the Father seeks. 24 God is spirit, and his worshipers must worship in the Spirit and in truth.',
    '34 Instead, one of the soldiers pierced Jesus’ side with a spear, bringing a sudden flow of blood and water.',
    '23 The Lord answered Moses, “Is the Lord’s arm too short? Now you will see whether or not what I say will come true for you.',
    '23 My angel will go ahead of you and bring you into the land of the Amorites, Hittites, Perizzites, Canaanites, Hivites and Jebusites, and I will wipe them out. 24 Do not bow down before their gods or worship them or follow their practices. You must demolish them and break their sacred stones to pieces. 25 Worship the Lord your God, and his blessing will be on your food and water. I will take away sickness from among you, 26 and none will miscarry or be barren in your land. I will give you a full life span.',
    '14 You will be blessed more than any other people; none of your men or women will be childless, nor will any of your livestock be without young. 15 The Lord will keep you free from every disease. He will not inflict on you the horrible diseases you knew in Egypt, but he will inflict them on all who hate you.',
    '8 From the Lord comes deliverance. May your blessing be on your people.',
    '2 I will bow down toward your holy temple and will praise your name for your unfailing love and your faithfulness, for you have so exalted your solemn decree that it surpasses your fame. 3 When I called, you answered me; you greatly emboldened me. 4 May all the kings of the earth praise you, Lord, when they hear what you have decreed. 5 May they sing of the ways of the Lord, for the glory of the Lord is great. 6 Though the Lord is exalted, he looks kindly on the lowly; though lofty, he sees them from afar. 7 Though I walk in the midst of trouble, you preserve my life. You stretch out your hand against the anger of my foes; with your right hand you save me. 8 The Lord will vindicate me; your love, Lord, endures forever— do not abandon the works of your hands.',
    '5 For his anger lasts only a moment, but his favor lasts a lifetime; weeping may stay for the night, but rejoicing comes in the morning.',
    '27 You save the humble but bring low those whose eyes are haughty.',
    '5 “Every word of God is flawless; he is a shield to those who take refuge in him.',
    '3 Let love and faithfulness never leave you; bind them around your neck, write them on the tablet of your heart. 4 Then you will win favor and a good name in the sight of God and man. 5 Trust in the Lord with all your heart and lean not on your own understanding;',
    '4 Take delight in the Lord, and he will give you the desires of your heart. 5 Commit your way to the Lord; trust in him and he will do this:',
    '7 The law of the Lord is perfect, refreshing the soul. The statutes of the Lord are trustworthy, making wise the simple.',
    '10 Create in me a pure heart, O God, and renew a steadfast spirit within me. 11 Do not cast me from your presence or take your Holy Spirit from me.',
    '3 If you, Lord, kept a record of sins, Lord, who could stand? 4 But with you there is forgiveness, so that we can, with reverence, serve you.',
    '1 Unless the Lord builds the house, the builders labor in vain. Unless the Lord watches over the city, the guards stand watch in vain. 2 In vain you rise early and stay up late, toiling for food to eat— for he grants sleep to[a] those he loves.',
    '6 “I said, ‘You are “gods”; you are all sons of the Most High.',
    '1 Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.[a]',
    '11 For he will command his angels concerning you to guard you in all your ways; 12 they will lift you up in their hands, so that you will not strike your foot against a stone. 13 You will tread on the lion and the cobra; you will trample the great lion and the serpent. 14 “Because he[a] loves me,” says the Lord, “I will rescue him; I will protect him, for he acknowledges my name. 15 He will call on me, and I will answer him; I will be with him in trouble, I will deliver him and honor him. 16 With long life I will satisfy him and show him my salvation.',
    '14 As for me, I will always have hope; I will praise you more and more. 15 My mouth will tell of your righteous deeds, of your saving acts all day long— though I know not how to relate them all.',
    '3 When the wine was gone, Jesus’ mother said to him, “They have no more wine.” 4 “Woman,[a] why do you involve me?” Jesus replied. “My hour has not yet come.” 5 His mother said to the servants, “Do whatever he tells you.” 6 Nearby stood six stone water jars, the kind used by the Jews for ceremonial washing, each holding from twenty to thirty gallons.[b] 7 Jesus said to the servants, “Fill the jars with water”; so they filled them to the brim. 8 Then he told them, “Now draw some out and take it to the master of the banquet.” They did so, 9 and the master of the banquet tasted the water that had been turned into wine. He did not realize where it had come from, though the servants who had drawn the water knew. Then he called the bridegroom aside 10 and said, “Everyone brings out the choice wine first and then the cheaper wine after the guests have had too much to drink; but you have saved the best till now.',
    '63 The Spirit gives life; the flesh counts for nothing. The words I have spoken to you—they are full of the Spirit[a] and life.',
    '10 The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.',
    '30 I and the Father are one.',
    '7 For there are three that testify: 8 the[a] Spirit, the water and the blood; and the three are in agreement',
    '7 Cast all your anxiety on him because he cares for you.',
    '6 Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.',
    '3 For you died, and your life is now hidden with Christ in God.',
    '8 But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.',
    '6 Annas the high priest was there, and so were Caiaphas, John, Alexander and others of the high priest’s family.',
    '5 and from Jesus Christ, who is the faithful witness, the firstborn from the dead, and the ruler of the kings of the earth. To him who loves us and has freed us from our sins by his blood,',
    '51 At that moment the curtain of the temple was torn in two from top to bottom. The earth shook, the rocks split 52 and the tombs broke open. The bodies of many holy people who had died were raised to life.',
    '19 I have given you authority to trample on snakes and scorpions and to overcome all the power of the enemy; nothing will harm you.',
    '28 So tell them, ‘As surely as I live, declares the Lord, I will do to you the very thing I heard you say',
    '23 The Lord answered Moses, “Is the Lord’s arm too short? Now you will see whether or not what I say will come true for you.',
    '23 If you return to the Almighty, you will be restored: If you remove wickedness far from your tent 24 and assign your nuggets to the dust, your gold of Ophir to the rocks in the ravines, 25 then the Almighty will be your gold, the choicest silver for you. 26 Surely then you will find delight in the Almighty and will lift up your face to God. 27 You will pray to him, and he will hear you, and you will fulfill your vows. 28 What you decide on will be done, and light will shine on your ways.',
    '13 But he stands alone, and who can oppose him? He does whatever he pleases.',
    '9 He performs wonders that cannot be fathomed, miracles that cannot be counted.',
    '2 “Dominion and awe belong to God; he establishes order in the heights of heaven.',
    '25 I know that my redeemer[a] lives, and that in the end he will stand on the earth.[b]',
    '6 So he said to me, “This is the word of the Lord to Zerubbabel: ‘Not by might nor by power, but by my Spirit,’ says the Lord Almighty.',
    '5 And I myself will be a wall of fire around it,’ declares the Lord, ‘and I will be its glory within.',
    '8 Come near to God and he will come near to you. Wash your hands, you sinners, and purify your hearts, you double-minded.',
    '14 Is anyone among you sick? Let them call the elders of the church to pray over them and anoint them with oil in the name of the Lord. 15 And the prayer offered in faith will make the sick person well; the Lord will raise them up. If they have sinned, they will be forgiven. 16 Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective.',
    '8 But the cowardly, the unbelieving, the vile, the murderers, the sexually immoral, those who practice magic arts, the idolaters and all liars—they will be consigned to the fiery lake of burning sulfur. This is the second death.',
    '1 The Lord is my light and my salvation— whom shall I fear? The Lord is the stronghold of my life— of whom shall I be afraid? 2 When the wicked advance against me to devour[a] me, it is my enemies and my foes who will stumble and fall. 3 Though an army besiege me, my heart will not fear; though war break out against me, even then I will be confident.',
    '17 Sanctify them by[a] the truth; your word is truth.',
    '5 “I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing.',
    '19 If you belonged to the world, it would love you as its own. As it is, you do not belong to the world, but I have chosen you out of the world. That is why the world hates you.',
    '35 By this everyone will know that you are my disciples, if you love one another.',
    '7 Blessed are the merciful, for they will be shown mercy.',
    '24 “No one can serve two masters. Either you will hate the one and love the other, or you will be devoted to the one and despise the other. You cannot serve both God and money.',
    '14 For if you forgive other people when they sin against you, your heavenly Father will also forgive you. 15 But if you do not forgive others their sins, your Father will not forgive your sins.',
    'Do not judge, or you too will be judged. 2 For in the same way you judge others, you will be judged, and with the measure you use, it will be measured to you. 3 “Why do you look at the speck of sawdust in your brother’s eye and pay no attention to the plank in your own eye?',
    '13 But go and learn what this means: ‘I desire mercy, not sacrifice.’[a] For I have not come to call the righteous, but sinners.',
    '30 And do not grieve the Holy Spirit of God, with whom you were sealed for the day of redemption.',
    'Now faith is confidence in what we hope for and assurance about what we do not see.',
    '23 “Truly[a] I tell you, if anyone says to this mountain, ‘Go, throw yourself into the sea,’ and does not doubt in their heart but believes that what they say will happen, it will be done for them.',
    '5 he saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit,',
    '10 For the love of money is a root of all kinds of evil. Some people, eager for money, have wandered from the faith and pierced themselves with many griefs.',
    '3 If anyone teaches otherwise and does not agree to the sound instruction of our Lord Jesus Christ and to godly teaching,',
    '10 Finally, be strong in the Lord and in his mighty power. 11 Put on the full armor of God, so that you can take your stand against the devil’s schemes. 12 For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms. 13 Therefore put on the full armor of God, so that when the day of evil comes, you may be able to stand your ground, and after you have done everything, to stand. 14 Stand firm then, with the belt of truth buckled around your waist, with the breastplate of righteousness in place, 15 and with your feet fitted with the readiness that comes from the gospel of peace. 16 In addition to all this, take up the shield of faith, with which you can extinguish all the flaming arrows of the evil one. 17 Take the helmet of salvation and the sword of the Spirit, which is the word of God.',
    '18 And pray in the Spirit on all occasions with all kinds of prayers and requests. With this in mind, be alert and always keep on praying for all the Lord’s people.',
    '16 So I say, walk by the Spirit, and you will not gratify the desires of the flesh. 17 For the flesh desires what is contrary to the Spirit, and the Spirit what is contrary to the flesh. They are in conflict with each other, so that you are not to do whatever[a] you want. 18 But if you are led by the Spirit, you are not under the law. 19 The acts of the flesh are obvious: sexual immorality, impurity and debauchery; 20 idolatry and witchcraft; hatred, discord, jealousy, fits of rage, selfish ambition, dissensions, factions 21 and envy; drunkenness, orgies, and the like. I warn you, as I did before, that those who live like this will not inherit the kingdom of God. 22 But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness,',
    '7 Do not be deceived: God cannot be mocked. A man reaps what he sows. 8 Whoever sows to please their flesh, from the flesh will reap destruction; whoever sows to please the Spirit, from the Spirit will reap eternal life.',
    '8 Whoever sows to please their flesh, from the flesh will reap destruction; whoever sows to please the Spirit, from the Spirit will reap eternal life.',
    '8 For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God',
    '5 which was not made known to people in other generations as it has now been revealed by the Spirit to God’s holy apostles and prophets.',
    '5 For if we have been united with him in a death like his, we will certainly also be united with him in a resurrection like his. 6 For we know that our old self was crucified with him so that the body ruled by sin might be done away with,[a] that we should no longer be slaves to sin— 7 because anyone who has died has been set free from sin.',
    'Paul, an apostle of Christ Jesus by the will of God, To God’s holy people in Ephesus,[a] the faithful in Christ Jesus: 2 Grace and peace to you from God our Father and the Lord Jesus Christ.',
    '13 For if you live according to the flesh, you will die; but if by the Spirit you put to death the misdeeds of the body, you will live.',
    '14 For those who are led by the Spirit of God are the children of God.',
    '10 But if Christ is in you, then even though your body is subject to death because of sin, the Spirit gives life[a] because of righteousness. 11 And if the Spirit of him who raised Jesus from the dead is living in you, he who raised Christ from the dead will also give life to your mortal bodies because of[b] his Spirit who lives in you.',
    '26 In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans.',
    '28 And we know that in all things God works for the good of those who love him, who[a] have been called according to his purpose.',
    '31 What, then, shall we say in response to these things? If God is for us, who can be against us? 32 He who did not spare his own Son, but gave him up for us all—how will he not also, along with him, graciously give us all things?',
    '35 Who shall separate us from the love of Christ? Shall trouble or hardship or persecution or famine or nakedness or danger or sword? 36 As it is written: “For your sake we face death all day long; we are considered as sheep to be slaughtered.”[a] 37 No, in all these things we are more than conquerors through him who loved us.',
    '10 For it is with your heart that you believe and are justified, and it is with your mouth that you profess your faith and are saved. 11 As Scripture says, “Anyone who believes in him will never be put to shame.”[a]',
    '11 Give back to them immediately their fields, vineyards, olive groves and houses, and also the interest you are charging them—one percent of the money, grain, new wine and olive oil.',
    'But the angel of the Lord went down with Azarias and his companions into the furnace: and he drove the flame of the fire out of the furnace',
    'Let them know that you alone are the Lord God, glorious over the whole world.',
    '28 but there is a God in heaven who reveals mysteries. He has shown King Nebuchadnezzar what will happen in days to come. Your dream and the visions that passed through your mind as you were lying in bed are these',
    '3 ‘Call to me and I will answer you and tell you great and unsearchable things you do not know.',
    '27 “I am the Lord, the God of all mankind. Is anything too hard for me?',
    '33 “This is the covenant I will make with the people of Israel after that time,” declares the Lord. “I will put my law in their minds and write it on their hearts. I will be their God, and they will be my people. 34 No longer will they teach their neighbor, or say to one another, ‘Know the Lord,’ because they will all know me, from the least of them to the greatest,” declares the Lord. “For I will forgive their wickedness and will remember their sins no more.”',
    '19 great are your purposes and mighty are your deeds. Your eyes are open to the ways of all mankind; you reward each person according to their conduct and as their deeds deserve.',
    'I was pushed back and about to fall, but the Lord helped me.',
    '5 Then I set bowls full of wine and some cups before the Rekabites and said to them, “Drink some wine.',
    '22 Because of the Lord’s great love we are not consumed, for his compassions never fail. 23 They are new every morning; great is your faithfulness. 24 I say to myself, “The Lord is my portion; therefore I will wait for him.” 25 The Lord is good to those whose hope is in him, to the one who seeks him; 26 it is good to wait quietly for the salvation of the Lord.',
    '37 Who can speak and have it happen if the Lord has not decreed it?',
    'May all of your creation serve you; you spoke, and they came into being. You sent forth your spirit and it shaped them; there is no one who can resist your voice.',
    'For their tongue that is polished by the craftsman, and themselves laid over with gold and silver, are false things, and they cannot speak.',
    '35 He is our God, and there is none like him. ',
    '6 My people are doomed because they do not acknowledge me. You priests have refused to acknowledge me and have rejected my teaching, and so I reject you and will not acknowledge your sons as my priests.',
    '8 Their tongues are smoothed by the craftsman, and they themselves are overlaid with gold and silver; but they are false and cannot speak. ',
    '12 For I know how many are your transgressions, and how great are your sins— you who afflict the righteous, who take a bribe, and turn aside the needy in the gate.',
    '13 and rend your hearts and not your garments.” Return to the Lord, your God, for he is gracious and merciful, slow to anger, and abounding in steadfast love, and repents of evil.',
    '25 I will restore to you the years which the swarming locust has eaten, the hopper, the destroyer, and the cutter, my great army, which I sent among you. 26 “You shall eat in plenty and be satisfied, and praise the name of the Lord your God, who has dealt wondrously with you. And my people shall never again be put to shame. 27 You shall know that I am in the midst of Israel, and that I, the Lord, am your God and there is none else. And my people shall never again be put to shame.',
    '6 Seek the Lord and live, lest he break out like fire in the house of Joseph, and it devour, with none to quench it for Bethel,',
    '3 God came from Teman, and the Holy One from Mount Paran. His glory covered the heavens, and the earth was full of his praise.',
    '17 The Lord your God is in your midst, a warrior who gives victory; he will rejoice over you with gladness, he will renew you[a] in his love; he will exult over you with loud singing 18 as on a day of festival.[b] “I will remove disaster[c] from you, so that you will not bear reproach for it. 19 Behold, at that time I will deal with all your oppressors. And I will save the lame and gather the outcast, and I will change their shame into praise and renown in all the earth.',
    '5 according to the promise that I made you when you came out of Egypt. My Spirit abides among you; fear not. 6 For thus says the Lord of hosts: Once again, in a little while, I will shake the heavens and the earth and the sea and the dry land; 7 and I will shake all nations, so that the treasures of all nations shall come in, and I will fill this house with splendor, says the Lord of hosts. 8 The silver is mine, and the gold is mine, says the Lord of hosts. 9 The latter splendor of this house shall be greater than the former, says the Lord of hosts; and in this place I will give prosperity, says the Lord of hosts.',
    '3 Therefore say to them, Thus says the Lord of hosts: Return to me, says the Lord of hosts, and I will return to you, says the Lord of hosts.',
    '39 So, my brethren, earnestly desire to prophesy, and do not forbid speaking in tongues',
    '4 He who speaks in a tongue edifies himself, but he who prophesies edifies the church. 5 Now I want you all to speak in tongues, but even more to prophesy. He who prophesies is greater than he who speaks in tongues, unless some one interprets, so that the church may be edified.',
    '4 Love is patient and kind; love is not jealous or boastful; 5 it is not arrogant or rude. Love does not insist on its own way; it is not irritable or resentful; 6 it does not rejoice at wrong, but rejoices in the right. 7 Love bears all things, believes all things, hopes all things, endures all things. 8 Love never ends; as for prophecies, they will pass away; as for tongues, they will cease; as for knowledge, it will pass away.',
    '20 For the kingdom of God does not consist in talk but in power.',
    'I appeal to you therefore, brethren, by the mercies of God, to present your bodies as a living sacrifice, holy and acceptable to God, which is your spiritual worship. 2 Do not be conformed to this world[a] but be transformed by the renewal of your mind, that you may prove what is the will of God, what is good and acceptable and perfect.[b]',
  ];

  static const List<String> bibleList = [
    'Isa 43:1-2',
    'Isa 43:4-5',
    'Isa 44:8',
    'Isa 44:2',
    'Isa 45:17',
    'Isa 41:10-14',
    'Isa 31:8-9',
    'Isa 19:20',
    'Isa 14:24',
    'Jer 1:19',
    'Jer 1:7-9',
    'Isa 35:5',
    'Isa 34:16',
    'Luke 1:37',
    'Mark 10:27',
    'Mark 7:37',
    'Mark 1:40-42',
    'Mark 1:32-35',
    'Mark 4:35-41',
    'Mark 5:27-29',
    'Mark 5:36',
    'John 11:40',
    'John 8:24',
    'John 8:12',
    'John 8:35-36',
    'John 8:10',
    'Micah 3:8',
    'Mal 3:10',
    'Mal 2:14',
    'Mal 3:6',
    'Eze 13:21',
    'John 4:23-24',
    'John 19:34',
    'Num 11:23',
    'Exo 23:23-26',
    'Deu 7:14-15',
    'Psalm 3:8',
    'Psalm 138:2-8',
    'Psalm 30:5',
    'Psalm 18:27',
    'Pro 30:5',
    'Pro 3:3-5',
    'Psalm 37:4-5',
    'Psalm 19:7',
    'Psalm 51:10-11',
    'Psalm 130: 3-4',
    'Psalm 127:1-2',
    'Psalm 82:6',
    'Psalm 91:1',
    'Psalm 91:11-16',
    'Psalm 71:14-15',
    'John 2:3-10',
    'John 6:63',
    'John 10:10',
    'John 10:30',
    '1 John 5:7-8',
    '1 Peter 5:7',
    'Phil 4:6',
    'Col 3:3',
    'Acts 1:8',
    'Acts 4:6',
    'Rev 1:5',
    'Matt 27:51-52',
    'Luke 10:19',
    'Num 14: 28',
    'Num 11: 23',
    'Job 22:23-28',
    'Job 23:13',
    'Job 5:9',
    'Job 25:2',
    'Job 19:25',
    'Zech 4:6',
    'Zech 2:5',
    'James 4:8',
    'James 5:14-16',
    'Rev 21:8',
    'Psalm 27:1-3',
    'John 17:17',
    'John 15:5',
    'John 15:19',
    'John 13:35',
    'Matt 5:7',
    'Matt 6:24',
    'Matt 6:14-15',
    'Matt 7:1-3',
    'Matt 9:13',
    'Eph 4:30',
    'Heb 11:1',
    'Mark 11:23',
    'Titus 3:5',
    '1 Timothy 6:10',
    '1 Timothy 6:3',
    'Eph 6:10-17',
    'Eph 6:18',
    'Gal 5:16-22',
    'Gal 6:7-8',
    'Gal 6:8',
    'Eph 2:8',
    'Eph 3:5',
    'Rom 6:5-7',
    'Eph 1:1-4',
    'Rom 8:13',
    'Rom 8:14',
    'Rom 8:10-11',
    'Rom 8:26',
    'Rom 8:28',
    'Rom 8:31-32',
    'Rom 8:35-37',
    'Rom 10:10-11',
    'Neh 5:11',
    'Dan 3:49',
    'Dan 3:45',
    'Dan 2:28',
    'Jer 3:33',
    'Jer 32: 27',
    'Jer 31:33-34',
    'Jer 32:19',
    'Psalm 118:13',
    'Jer 35:5',
    'Lam 3:22-26',
    'Lam 3:37',
    'Judith 16:14',
    'Baruch 6:7',
    'Baruch 3:35',
    'Hosea 4:6',
    'Baruch 6:8',
    'Amos 5:12',
    'Joel 2:13',
    'Joel 2:25-27',
    'Amos 5:6',
    'Habakkuk 3:3',
    'Zeph 3:17-19',
    'Hag 2:5-9',
    'Zech 1:3',
    '1 cor 14:39',
    '1 Cor 14:4-5',
    '1 Cor 13:4-8',
    '1 Cor 4:20',
    'Rom 12:1-2',
  ];
}